### ISSUE TITLE
SyntaxError: ';' expected.

### ISSUE THREAD

**Issue by lastmjs** [gqless/gqless#102]
Hey!

It's my first time using gqless, and when I run `gqless generate` I get the following error:

```javascript
SyntaxError: ';' expected. (9095:6)
  9093 | * @type OBJECT
  9094 |  */
> 9095 | type t_HighLevelStatses = FieldsType<{
       |      ^
  9096 | __typename: t_String<'HighLevelStatses'>
  9097 | highLevelStats: t_HighLevelStats
  9098 | highLevelStatsForMonths: (t_HighLevelStatsForMonth)[]
    at t (~/development/jill/jills-office-web/node_modules/prettier/parser-typescript.js:1:285)
    at Object.parse (~/development/jill/jills-office-web/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (~/development/jill/jills-office-web/node_modules/prettier/index.js:9739:19)
    at coreFormat (~/development/jill/jills-office-web/node_modules/prettier/index.js:13252:23)
    at format (~/development/jill/jills-office-web/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (~/development/jill/jills-office-web/node_modules/prettier/index.js:13526:12)
    at ~/development/jill/jills-office-web/node_modules/prettier/index.js:44207:15
    at Object.format (~/development/jill/jills-office-web/node_modules/prettier/index.js:44226:12)
    at Object.exports.generateSchema (~/development/jill/jills-office-web/node_modules/@gqless/cli/dist/utils/generateSchema.js:25:33)
    at async Generate.run (~/development/jill/jills-office-web/node_modules/@gqless/cli/dist/commands/generate.js:27:9)
```

It looks like it's just some formatting after the generation takes place, I believe the generation succeeded, though I'm not quite sure.

**Comment by samdenty** [comment]
I've only tested gqless with spec-compliant schemas.
Stuff like this is caused in edge cases, where the introspection returned is bad.

I know this is currently breaking if you have an interface without implementations - but I'd have to debug further.
